# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarboppfolging
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarboppfolging/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarboppfolging/internal/isReady
    initialDay: 60
prometheus:
  enabled: true
  path: veilarboppfolging/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 1536Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarboppfolging
    resourceType: loadbalancerconfig
  - alias: veilarboppfolgingDB
    resourceType: datasource
  - alias: srvveilarboppfolging
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: veilarboppfolging.properties
    resourceType: applicationproperties
  - alias: feed.brukertilgang
    resourceType: applicationproperties
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: abac.pdp.endpoint
    resourceType: restservice
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: unleash-api
    resourceType: restservice

  - alias: aktivitetsplan
    resourceType: baseurl
  - alias: veilArbAktivitetAPI
    resourceType: restservice
  - alias: virksomhet:DigitalKontakinformasjon_v1
    resourceType: webserviceendpoint
  - alias: virksomhet:Ytelseskontrakt_v3
    resourceType: webserviceendpoint
  - alias: virksomhet:Oppfolging_v1
    resourceType: webserviceendpoint
  - alias: virksomhet:Oppfoelgingsstatus_v2
    resourceType: webserviceendpoint
  - alias: virksomhet:OrganisasjonEnhet_v2
    resourceType: webserviceendpoint
  - alias: Varseloppgave_v1
    resourceType: webserviceendpoint
  - alias: virksomhet:BehandleArbeidssoeker_v1
    resourceType: webserviceendpoint
  - alias: kafka-brokers
    resourceType: baseurl
  - alias: veilarbarenaAPI
    resourceType: restservice

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: veilarbazureadproxy_discovery
    resourceType: restservice

  - alias: security-token-service-openid-configuration
    resourceType: restservice

  exposed:
  - alias: veilArbOppfolgingAPI
    resourceType: restservice
    path: /veilarboppfolging/api

alertProfiles:
  - common-java-modules
