kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: default
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging.nais.adeo.no
    - https://app.adeo.no/veilarboppfolging
    - https://app.adeo.no/veilarboppfolging-ws
  leaderElection: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/metrics
  liveness:
    path: veilarboppfolging/internal/isAlive
    port: 8080
    initialDelay: 20
  readiness:
    path: veilarboppfolging/internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
  envFrom:
    - configmap: pto-config
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: VEILARBOPPFOLGINGDB_URL
      value: jdbc:oracle:thin:@a01dbfl037.adeo.no:1521/veilarboppfolging
    - name: ROLE
      value: 0000-GA-Modia-Oppfolging
    - name: LDAP_FALLBACK
      value: "false"
    - name: FEATURE_SKIP_VALIDERING_DIFI
      value: "false"
    - name: KVP_API_BRUKERTILGANG
      value: srvveilarbdialog,srvveilarbaktivitet
    - name: MIN_ALDER_AUTOMATISK_REGISTRERING
      value: "0"
    - name: MAKS_ALDER_AUTOMATISK_REGISTRERING
      value: "0"
    - name: ESKALERINGSVARSEL_VARSELTYPE
      value: DittNAV_000008
    - name: ESKALERINGSVARSEL_OPPGAVETYPE
      value: "0004"
    - name: AVSLUTTETOPPFOLGING_FEED_BRUKERTILGANG
      value: srvveilarbdialog,srvveilarbaktivitet,srvveilarbjobbsoke
    - name: KVP_FEED_BRUKERTILGANG
      value: srvveilarbdialog,srvveilarbaktivitet
    - name: NYEBRUKERE_FEED_BRUKERTILGANG
      value: srvveilarbdirigent
    - name: OPPFOLGING_FEED_BRUKERTILGANG
      value: srvveilarbportefolje
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarboppfolging-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarboppfolging/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
