kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: poao
  labels:
    team: poao
spec:
  image: {{image}}
  ingresses:
    - https://veilarboppfolging.intern.dev.nav.no
  port: 8080
  gcp:
    sqlInstances:
      - name: veilarboppfolging
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        diskAutoresize: true
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: veilarboppfolging
            envVarPrefix: DB
            users:
              - name: datastream
              - name: veilarboppfolging_midlertidig # Bruker uten write-rettigheter
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/health/liveness
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/health/readiness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: http://digdir-krr-proxy.team-rocket
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: AMTTILTAK_URL
      value: http://amt-tiltak.amt
    - name: AMTTILTAK_SCOPE
      value: api://dev-gcp.amt.amt-tiltak/.default
    - name: KAFKA_ENABLED
      value: "false"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: paw-proxy
          namespace: paw
        - application: veilarbperson
          namespace: pto
          cluster: dev-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: modia-robot-api
          namespace: personoversikt
          cluster: dev-fss
        - application: modia-robot-api
          namespace: personoversikt
          cluster: dev-gcp
        - application: modiapersonoversikt-api-q1
          namespace: personoversikt
          cluster: dev-fss
        - application: ditt-sykefravaer
          namespace: flex
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: veilarbdialog
          namespace: pto
          cluster: dev-fss
        - application: veilarbdialog
          namespace: dab
          cluster: dev-gcp
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
        - application: esyfo-info-frontend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: amt-person-service
          namespace: amt
          cluster: dev-gcp
        - application: tms-min-side-proxy
          namespace: min-side
          cluster: dev-gcp
        - application: tms-mikrofrontend-selector
          namespace: min-side
          cluster: dev-gcp
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: amt-distribusjon
          namespace: amt
          cluster: dev-gcp
        - application: dokumentfordeling
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
