kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarboppfolging
    - https://app-q1.dev.adeo.no/veilarboppfolging
  leaderElection: true
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarboppfolging_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarboppfolging/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarboppfolging_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
  env:
    - name: MODIABLOGIN_OPENAM_CLIENT_ID
      value: "modialogin-q1"

    # consumer topic
    - name: ENDRING_PAA_OPPFOELGINGSBRUKER_TOPIC
      value: aapen-fo-endringPaaOppfoelgingsBruker-v1-q1

    # producer topics
    - name: ENDRING_PAA_AVSLUTT_OPPFOLGING_TOPIC
      value: aapen-fo-endringPaaAvsluttOppfolging-v1-q1
    - name: OPPFOLGING_STARTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingStartet-v1-q1
    - name: OPPFOLGING_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-q1
    - name: KVP_STARTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpStartet-v1-q1
    - name: KVP_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpAvsluttet-v1-q1
    - name: ENDRING_PA_MANUELL_STATUS_TOPIC
      value: aapen-arbeidsrettetOppfolging-endringPaManuellStatus-v1-q1
    - name: VEILEDER_TILORDNET_TOPIC
      value: aapen-arbeidsrettetOppfolging-veilederTilordnet-v1-q1
    - name: ENDRING_PA_NY_FOR_VEILEDER_TOPIC
      value: aapen-arbeidsrettetOppfolging-endringPaNyForVeileder-v1-q1
    - name: ENDRING_PA_MAL_TOPIC
      value: aapen-arbeidsrettetOppfolging-endringPaMal-v1-q1